name: SHDFGamePlugin
version: '${version}'

main: com.sHDFGamePlugin.SHDFGamePlugin
paper-plugin-loader: com.sHDFGamePlugin.SHDFGamePluginLoader
api-version: '1.21.11'
load: POSTWORLD

depend:
  - ShadowHunterRolesPlugin

commands:
  shdfgame:
    description: "游戏主命令"
    usage: "/sg <config ...>"
    aliases:
      - "sg"
    permission: "shadowhunter.game.player"